FONT_FAMILY_PATH = "assets/Tiny5.ttf"

HUB_NAME_SIZE = 25
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

HUB_SIZE = 50
DRONE_SIZE = 50
DRONE_IMG = "assets/spaceship.png"


CONNECTION_LINE_SIZE = 5
CONNECTION_LINE_COLOR = "white"

HUB_GAP_HORIZONTAL = 300
HUB_GAP_VERTICAL = 200

HORIZONTAL_SHIFT = 100
VERTICAL_SHIFT = 300


MITRIX_TEXT_SIZE = 50
