FONT_FAMILY_PATH = "assets/Tiny5.ttf"

HUB_NAME_SIZE = 25
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
HUB_SIZE = 30
CONNECTION_LINE_SIZE = 2
CONNECTION_LINE_COLOR = "white"

HUB_GAP_HORIZONTAL = 30
HUB_GAP_VERTICAL = 30

HORIZONTAL_SHIFT = 100
VERTICAL_SHIFT = 500


MITRIX_TEXT_SIZE = 50
