class Validator:

    def validate(self, data: dict) -> None: ...
    def validate_hub(self): ...
    def validate_connection(self): ...
    def validate_hub_metadata(self): ...
    def validate_connection_metadata(self): ...


# implemet that later
